apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetry-generator
  template:
    metadata:
      labels:
        app: telemetry-generator
    spec:
      containers:
        - name: generator
          image: aiops-app:1.0
          command: ["python", "generator.py"]

