apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aiops-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: aiops.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aiops-app
                port:
                  number: 8000

