apiVersion: v1
kind: Service
metadata:
  name: aiops-app
spec:
  type: NodePort
  selector:
    app: aiops-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080  # You can access app at localhost:30080

